apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ch1h66udk-nodejs
  janus-idp.io/tekton: ch1h66udk-nodejs
  backstage.io/kubernetes-id: ch1h66udk-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: ch1h66udk-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
