apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ch1h66udk-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ch1h66udk-nodejs 
  name: ch1h66udk-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: ch1h66udk-nodejs 
